name: ci

on: [push, pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  # TODO: #572 - needs improvements
  # build:
  #   runs-on: ubuntu-latest
  #   name: Check
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@main
  #     - name: Check
  #       run: ./check.sh

  markdownlint:
    runs-on: ubuntu-latest
    name: Markdownlint
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Markdownlint
        uses: nosborn/github-action-markdown-cli@85611bef0da53168168939754ff9d8f6073a8fec
        with:
          files: "*.md"
          config_file: .markdownlint.json

  ensure_sorted:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: Ensure sorted
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Ensure sorted
        run: python3 ensure_sorted.py
