name: ci

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Check
        run: ./check.sh

  markdownlint:
    runs-on: ubuntu-latest
    name: Markdownlint
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Markdownlint
        uses: nosborn/github-action-markdown-cli@master
        with:
          files: "*.md"
          config_file: .markdownlint.json

  ensure_sorted:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: Ensure sorted
    steps:
      - name: Ensure sorted
        run: python3 ./ensure_sorted.py

